# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.3.9-cli-stretch-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Upgrade node (so we can continue to support PHP 7.2)
      - run: sudo npm cache clean -f && sudo npm install -g n && sudo n stable

      # Install GD extension
      # CircleCI: It does not work, bro
      # Me: Try again
      # CircleCI: Cool, I got dis
      # https://discuss.circleci.com/t/apt-get-error-exited-with-code-100/26722/5
      - run: sudo apt-get update -y || sudo apt-get update -y
      - run: sudo apt-get install -y libpng-dev
      - run: sudo docker-php-ext-install gd

      # Restore Composer cache
      - restore_cache:
          keys:
            - composer-dependencies-{{ checksum "composer.json" }}
            - composer-dependencies-

      # Execute Composer install
      - run: composer --no-interaction --optimize-autoloader install

      # Save Composer cache
      - save_cache:
          paths:
            - ./vendor
          key: composer-dependencies-{{ checksum "composer.json" }}

      # Restore Yarn cache
      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "yarn.lock" }}

      # Execute Yarn install and build
      - run: yarn install
      - run: yarn build

      # Save Yarn cache
      - save_cache:
          paths:
            - ./node_modules
          key: yarn-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: ./vendor/bin/phpunit
